const answers = {
  "City Water": "Or Municipal Water, it usually comes from public water systems—such as reservoirs, rivers, lakes, or underground wells—and public water must meet safety and quality standards such as adding Chlorine before being delivered through pipes to your tap.\nSolution: Reverse Osmosis, Ion Exchange with Activated Carbon",
  
  "Well Water": "Well water is water drawn directly from an underground aquifer using a well, rather than being supplied by a city’s municipal system. A hole is drilled into the ground until it reaches an aquifer (a layer of water-bearing rock or sand).  A pump brings the water up through pipes to your home.  The water usually bypasses centralized treatment plants, so the homeowner is responsible for testing and treatment.  Private wells have no regulations to meet safety standards.\nSolution: Reverse Osmosis, Ion Exchange, UV Treatment",
  
  "Hard Water": "Hard water is water that contains a high concentration of dissolved minerals, mainly calcium and magnesium ions.  These minerals usually come from groundwater flowing through limestone, chalk, or gypsum deposits.  Soap doesn’t lather easily and leaves a scummy residue.  White or chalky deposits (limescale) build up on faucets, showerheads, or inside cooking pots.  Clothes may feel stiff after washing.  Glassware can get cloudy spots after drying. Damaging to hot water appliances\nSolution: Ion Exchange",
  
  "Soft Water": "Soft water is water that has low concentrations of calcium and magnesium ions—the minerals that make water “hard.” Natural soft water is often from rainfall, lakes, and rivers in areas without much mineral-rich rock.  Artificially softened water is produced by water softeners that replace calcium and magnesium with sodium ions. Characteristics:  Soap lathers easily and rinses away cleanly.  No white scale buildup in kettles, coffee makers, or showerheads.  Clothes feel softer after washing. Can feel “slippery” or “silky” on the skin after bathing because soap doesn’t bind to minerals.",
  
  "Corrosion": "Corrosion is the gradual destruction or deterioration of a material—usually metal—caused by a chemical or electrochemical reaction with its environment.\nIn simple terms, it’s when metal reacts with substances like oxygen, water, acids, or limescale and slowly deteriorates the metal.  Weakens structures and equipment (bridges, water pipes, cars).  Can cause leaks in plumbing.  In water systems, corrosion can release metals like lead or copper into drinking water.\nSolution: Ion Exchange with Activated Carbon",
  
  "Limescale": "Limescale is a hard, chalky deposit that forms when hard water (rich in calcium and magnesium) is heated or left standing.  Mostly calcium carbonate (CaCO₃), sometimes mixed with magnesium compounds.  Hard water contains calcium and magnesium bicarbonates.  When heated, these bicarbonates break down into carbonates.  Carbonates are less soluble, so they come out of solution and stick to surfaces resulting in reduced appliance efficiency, shortens lifespan of water heaters and kettles, makes cleaning harder and can dull shiny surfaces and soap binds within the water.\nSolution: Ion Exchange with Activated Carbon",
  
  "Soap Scum": "Soap scum is the filmy, chalky residue that forms when soap reacts with minerals in hard water.  A mix of calcium stearate and magnesium stearate (the insoluble salts of soap’s fatty acids).  Can also trap dirt, body oils, and bacteria.  Soap molecules have fatty acid salts that dissolve well in soft water.  In hard water, calcium and magnesium ions replace the sodium in soap, creating insoluble compounds.  These compounds stick to surfaces, making that cloudy film on shower doors, tiles, bathtubs, and sinks and on hair and skin causing itchy and dryness.  Can trap mildew and bacteria and difficult to remove with normal cleaning—often needs acidic cleaners or scrubbing.\nSolution: Ion Exchange with Activated Carbon",
  
  "Spring Water": "Spring water is water that flows naturally from an underground source to the Earth’s surface, often through cracks in rock or soil. Rain and snow seep into the ground and travel through layers of soil and rock.  Along the way, the water gets filtered naturally and dissolves minerals.  When it reaches a point where the pressure pushes it up to the surface, it forms a spring.  Often contains minerals like calcium, magnesium, and potassium.  Can vary widely in taste and mineral content depending on the geology of the area.  Usually clear, but not automatically free of microbes—needs testing before drinking.  Bottled Spring Water is taken directly from underground springs but meets regulatory standards.",
  
  "Purified Water": "Purified water is water that has been mechanically filtered or processed to remove impurities, contaminants, and most dissolved minerals, making it extremely clean. Typically 99% free of dissolved solids, chemicals, and microbes. Can come from any source (tap, well, spring) before purification. Extremely pure—ideal for drinking water.",
  
  "Distilled Water": "Distilled water is water that has been purified by boiling it into steam and then condensing that steam back into liquid—leaving behind most minerals, salts, and impurities.  Extremely pure—almost no dissolved minerals or salts.  Can come from any original source (tap, well, spring) before distillation.  Slightly acidic pH due to absorbing carbon dioxide from the air. Very “flat” taste.  Ideal for laboratory experiments, medical equipment and car batteries and steam irons.",
  
  "Alkaline Water": "Alkaline water is water that has a higher pH than regular drinking water—usually pH 8–9 instead of the typical ~pH 7.  Sometimes it’s naturally alkaline (from flowing over mineral-rich rocks).  Other times it’s made alkaline by ionization machines or adding alkaline minerals.  Health claims: Some marketing says alkaline water can neutralize acid in the body, improve hydration, and boost health. Scientific evidence: Most people’s bodies regulate blood pH tightly regardless of water type, so proven health benefits are limited—though some studies suggest it may help with acid reflux or hydration in certain cases.\nSolution: Add Baking Soda",
  
  "UV Treatment": "Ultraviolet (UV) treatment is a water disinfection method that uses ultraviolet light to kill or inactivate microorganisms like bacteria, viruses, and protozoa—without adding chemicals.  Best for homes using private well water.  Water flows through a chamber containing a UV lamp. The UV light (specifically UV-C, around 254 nanometers) damages the DNA or RNA of microorganisms. This prevents them from reproducing and causing illness. Disinfection happens almost instantly as water passes the lamp.  No chemical taste or byproducts (unlike chlorine). Works continuously and automatically once installed. Low maintenance aside from changing the lamp annually.",
  
  "Ion Exchange": "Ion exchange is a water treatment process that swaps unwanted dissolved mineral ions in water for more desirable ones, using a special medium called ion exchange resin.  Water passes through resin beads that carry charged + sodium ions.  Unwanted ions in the water attach to the resin.  Over time, the resin becomes “full” and must be regenerated with a concentrated brine solution.  Water softening Ion Exchange is only science-based process to remove hardness minerals (calcium, magnesium) that prevents limescale in pipes and appliances using hot water.",
  
  "Reverse Osmosis": "Reverse osmosis (RO) is a water purification process that uses a semi-permeable membrane to remove dissolved salts, minerals, and other impurities from water.  Water is pushed under pressure through a special membrane with extremely tiny pores (~0.0001 microns).  The rejected impurities are flushed away as wastewater.  What it removes:  Dissolved salts and minerals (calcium, magnesium, sodium).  Heavy metals (lead, arsenic, mercury).  Microorganisms (bacteria, protozoa, some viruses).  Many chemicals (nitrates, fluoride, pesticides).  Produces very pure water—often >95–99% of dissolved solids removed.  Improves taste and odor by removing chlorine and contaminants.",
  
  "Chlorine": "Chlorine is a chemical element (symbol Cl) commonly used in water treatment as a disinfectant to kill harmful microorganisms like bacteria, viruses, and parasites. Usually added as chlorine gas, sodium hypochlorite (liquid bleach), or calcium hypochlorite (solid form).  Works by breaking down cell walls and disrupting the metabolism of microbes.  Leaves a residual amount in pipes, helping keep water safe as it travels to taps. Very effective and relatively inexpensive. Provides ongoing protection during distribution. Widely used and well-studied. Can give water a “bleach-like” taste or smell.  Reacts with natural organic matter to form disinfection byproducts (like trihalomethanes, THMs) that can be harmful in high amounts. Doesn’t remove all chemical pollutants or dissolved solids. Chlorine is a poisonous gas.\nSolution: Reverse Osmosis, Ion Exchange with Activated Carbon",
  
  "Natural Soft Water replaces Calcium": "Natural soft water is water that naturally contains low levels of calcium and magnesium ions, so it doesn’t cause the scaling and soap scum problems associated with hard water—without needing artificial softening.  Found in regions where rainwater or surface water hasn’t flowed through mineral-rich rocks like limestone or chalk.  Common in areas with granite, sandstone, or volcanic rock, which don’t easily release calcium or magnesium.  Many lakes, rivers, and reservoirs in such regions supply naturally soft water.  Soap lathers easily.  No limescale buildup in kettles, heaters, or pipes.  Can feel “silky” or “slippery” on the skin. Still may contain other minerals, but in low hardness levels.  Gentle on plumbing and appliances.  Reduces need for water softeners. Less detergent and cleaning product needed and better for your hair and skin.",
  
  "Sulfur": "Sulfur is a chemical element (symbol S) found naturally in rocks, soil, water, and living organisms. Usually appears as sulfates (SO₄²⁻) or hydrogen sulfide gas (H₂S). Sulfates occur when water passes through soil or rock containing gypsum or other sulfur minerals. Hydrogen sulfide can form in groundwater with certain bacteria that break down organic matter without oxygen—this is what gives some well water that “rotten egg” smell.  Sulfates: High levels can cause a bitter taste and, in large amounts, digestive issues (laxative effect). Hydrogen sulfide: Strong unpleasant odor, can corrode pipes, and can tarnish metals like silver.  Hydrogen sulfide can damage plumbing and appliances.\nSolution: Reverse Osmosis, Ion Exchange, Distillation, Aeration",
  
  "Bacteria": "Bacteria are microscopic, single-celled organisms found almost everywhere—including soil, water, food, and inside living beings.  Many bacteria are harmless or even beneficial.  Some, however, are pathogenic (disease-causing) and can make water unsafe to drink.  Common harmful waterborne bacteria include: Escherichia coli (E. coli) – some strains cause diarrhea and illness. Salmonella – causes typhoid fever or gastroenteritis. Vibrio cholerae – causes cholera.  Contamination from human or animal waste.  Runoff from farms or septic systems.  Breaks or leaks in water distribution pipes. Flooding that mixes sewage and drinking water.\nSolution: Reverse Osmosis, Ozonation, UV Treatment",
  
  "Pesticides": "Pesticides are chemicals used to kill or control pests—including insects, weeds, fungi, and rodents—in agriculture, landscaping, and public health programs.  They can enter rivers, lakes, and groundwater through agricultural runoff, lawn care, industrial discharge, or improper disposal.  Common types found in water include herbicides (weed killers), insecticides, and fungicides.  Many pesticides contain compounds that can be toxic to humans, animals, and aquatic life.  Long-term exposure—even at low levels—can increase risks of certain cancers, hormone disruption, or nervous system effects. Some pesticides break down slowly, so they persist in the environment and build up in the food chain.\nSolution: Reverse Osmosis, Distillation",
  
  "E. Coli": "(Escherichia coli) is a type of bacteria commonly found in the intestines of humans and warm-blooded animals.  Most strains are harmless and even help with digestion.  Presence of any E. coli in drinking water is a warning sign of fecal contamination, meaning other harmful microbes may also be present.  Leakage from septic tanks or sewer lines.  Runoff from livestock farms or manure use.  Contamination from wildlife waste.  Cross-connections or breaks in water pipes.  In severe cases, can cause kidney damage (hemolytic uremic syndrome, HUS), especially in children and the elderly.\nSolution: Reverse Osmosis, UV Treatment",
  
  "Heavy Metals": "Heavy metals are naturally occurring metallic elements with a high atomic weight and density, and many of them can be toxic even in small amounts.  Common heavy metals of concern include lead, mercury, arsenic, cadmium, chromium, and copper.  They can enter water from:  Natural leaching from rocks and soils.  Corrosion of plumbing pipes and fixtures.  Industrial discharges and mining operations.  Agricultural runoff (fertilizers, pesticides).  Unlike many organic contaminants, heavy metals don’t break down easily. They can bio-accumulate in the body over time.\nSolution:  Reverse osmosis, Distillation, Activated Alumina and Ion exchange."
};
